# Generated by Django 5.1.6 on 2026-01-23 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbc', '0003_alter_learningarea_teacher'),
        ('students', '0004_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='cbc.gradelevel'),
        ),
    ]
