# Generated by Django 5.1.6 on 2026-01-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Carried forward overpayments', max_digits=10),
        ),
    ]
