# Generated by Django 5.1.6 on 2026-01-31 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbc', '0003_alter_learningarea_teacher'),
        ('events', '0001_initial'),
        ('students', '0006_student_credit_balance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='student',
            name='credit_balance',
        ),
        migrations.AddField(
            model_name='attendance',
            name='learning_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='cbc.learningarea'),
        ),
        migrations.AddField(
            model_name='student',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='events.club'),
        ),
    ]
