# Generated by Django 5.1.6 on 2026-01-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_quiz_due_date'),
        ('students', '0007_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', to='courses.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Carried forward overpayments', max_digits=10),
        ),
    ]
