# Generated by Django 5.1.6 on 2026-01-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventnotice',
            name='is_school_wide',
        ),
        migrations.AddField(
            model_name='eventnotice',
            name='target_type',
            field=models.CharField(choices=[('all', 'School-wide'), ('grades', 'Specific Grades'), ('clubs', 'Specific Clubs')], default='all', max_length=10),
        ),
    ]
