# Generated by Django 5.1.6 on 2026-01-23 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('curriculum_type', models.CharField(choices=[('CBC', 'Competency-Based Curriculum'), ('8-4-4', 'Traditional 8-4-4')], max_length=10)),
                ('order', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grade Level',
                'verbose_name_plural': 'Grade Levels',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LearningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_areas', to='cbc.gradelevel')),
                ('students', models.ManyToManyField(blank=True, related_name='learning_areas', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_areas', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Learning Area',
                'verbose_name_plural': 'Learning Areas',
                'ordering': ['grade_level', 'name'],
                'unique_together': {('name', 'grade_level')},
            },
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField()),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strands', to='cbc.learningarea')),
            ],
            options={
                'verbose_name': 'Strand',
                'verbose_name_plural': 'Strands',
                'ordering': ['learning_area', 'order'],
                'unique_together': {('learning_area', 'order')},
            },
        ),
        migrations.CreateModel(
            name='SubStrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField()),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_strands', to='cbc.strand')),
            ],
            options={
                'verbose_name': 'Sub-Strand',
                'verbose_name_plural': 'Sub-Strands',
                'ordering': ['strand', 'order'],
                'unique_together': {('strand', 'order')},
            },
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=50, unique=True)),
                ('order', models.IntegerField()),
                ('suggested_activities', models.TextField(blank=True, help_text='Suggested teaching activities')),
                ('sub_strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='cbc.substrand')),
            ],
            options={
                'verbose_name': 'Learning Outcome',
                'verbose_name_plural': 'Learning Outcomes',
                'ordering': ['sub_strand', 'order'],
                'unique_together': {('sub_strand', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CompetencyAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency_level', models.CharField(choices=[('EE', 'Exceeding Expectations'), ('ME', 'Meeting Expectations'), ('AE', 'Approaching Expectations'), ('BE', 'Below Expectations')], max_length=2)),
                ('assessment_date', models.DateField(auto_now_add=True)),
                ('teacher_comment', models.TextField(blank=True, help_text="Specific feedback on student's performance")),
                ('evidence', models.TextField(help_text='What the student did to demonstrate this competency')),
                ('assignment_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competency_assessments', to='courses.assignmentsubmission')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_assessments', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_assessments', to='teachers.teacher')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='cbc.learningoutcome')),
            ],
            options={
                'verbose_name': 'Competency Assessment',
                'verbose_name_plural': 'Competency Assessments',
                'ordering': ['-assessment_date'],
                'indexes': [models.Index(fields=['student', 'learning_outcome'], name='cbc_compete_student_518a11_idx'), models.Index(fields=['assessment_date'], name='cbc_compete_assessm_0328df_idx')],
            },
        ),
    ]
