# Generated by Django 5.1.6 on 2026-01-23 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbc', '0001_initial'),
        ('courses', '0004_assignment_assessment_type_assignment_learning_area_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('photo', 'Photo'), ('document', 'Document'), ('observation', 'Observation Note'), ('video', 'Video')], max_length=15)),
                ('file_url', models.FileField(blank=True, null=True, upload_to='assessment_evidence/')),
                ('description', models.TextField(help_text='Description of the evidence')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('competency_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='cbc.competencyassessment')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkGradingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_submissions', models.IntegerField(default=0)),
                ('graded_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_sessions', to='courses.assignment')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_sessions', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Grade 4 Math - Addition'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of when to use this template')),
                ('criteria_ee', models.TextField(help_text='Exceeding Expectations criteria')),
                ('criteria_me', models.TextField(help_text='Meeting Expectations criteria')),
                ('criteria_ae', models.TextField(help_text='Approaching Expectations criteria')),
                ('criteria_be', models.TextField(help_text='Below Expectations criteria')),
                ('is_shared', models.BooleanField(default=False, help_text='Share with other teachers')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this template has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to='teachers.teacher')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_templates', to='cbc.gradelevel')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_templates', to='cbc.learningarea')),
            ],
            options={
                'ordering': ['-usage_count', '-created_at'],
                'indexes': [models.Index(fields=['learning_area', 'grade_level'], name='cbc_assessm_learnin_f535f6_idx'), models.Index(fields=['-usage_count'], name='cbc_assessm_usage_c_7f9bcb_idx')],
            },
        ),
    ]
