import jsPDF from 'jspdf';

/**
 * Generate a PDF from assignment description
 * @param {Object} assignment - Assignment object with title, description, due_date, total_marks
 */
export const generateAssignmentPDF = (assignment) => {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(20);
    doc.setFont(undefined, 'bold');
    doc.text('Assignment', 20, 20);

    // Title
    doc.setFontSize(16);
    doc.text(assignment.title, 20, 35);

    // Details
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text(`Due Date: ${new Date(assignment.due_date).toLocaleDateString()}`, 20, 45);
    doc.text(`Total Marks: ${assignment.total_marks}`, 20, 52);

    // Description
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text('Description:', 20, 65);

    doc.setFont(undefined, 'normal');
    doc.setFontSize(11);

    // Split description into lines (max width 170)
    const lines = doc.splitTextToSize(assignment.description || 'No description provided', 170);
    doc.text(lines, 20, 75);

    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(128);
    doc.text('Generated by SchoolOS', 20, pageHeight - 10);

    // Save
    const filename = `${assignment.title.replace(/[^a-z0-9]/gi, '_')}.pdf`;
    doc.save(filename);
};
