# Generated by Django 5.1.6 on 2026-01-26 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbc', '0003_alter_learningarea_teacher'),
        ('core', '0003_academicterm'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='academic_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='core.academicterm'),
        ),
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['-academic_term__start_date']},
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('grade_level', 'academic_term')},
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='term',
        ),
    ]
