# Generated by Django 5.1.6 on 2026-01-31 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('finance', '0002_alter_feestructure_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentfee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='event_notice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='events.eventnotice'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='finance.feestructure'),
        ),
    ]
