# Generated by Django 5.1.6 on 2026-01-23 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbc', '__first__'),
        ('courses', '0003_lesson_discussionthread_discussioncomment_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assessment_type',
            field=models.CharField(choices=[('formative', 'Formative Assessment'), ('summative', 'Summative Assessment')], default='formative', help_text='Type of CBC assessment', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='learning_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cbc.learningarea'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='learning_outcome',
            field=models.ForeignKey(blank=True, help_text='Specific learning outcome being assessed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='cbc.learningoutcome'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='competency_comment',
            field=models.TextField(blank=True, help_text="Teacher's comment on competency achievement"),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='competency_level',
            field=models.CharField(blank=True, choices=[('EE', 'Exceeding Expectations'), ('ME', 'Meeting Expectations'), ('AE', 'Approaching Expectations'), ('BE', 'Below Expectations')], help_text='CBC competency level achieved', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
