# Generated by Django 5.1.6 on 2026-01-23 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbc', '0003_alter_learningarea_teacher'),
        ('courses', '0004_assignment_assessment_type_assignment_learning_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_area',
            field=models.ForeignKey(blank=True, help_text='Link to the official CBC Learning Area registry entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_courses', to='cbc.learningarea'),
        ),
    ]
