# Generated by Django 5.1.6 on 2026-01-24 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbc', '0003_alter_learningarea_teacher'),
        ('courses', '0005_course_learning_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='learning_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lms_modules', to='cbc.learningarea'),
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['learning_area', 'order']},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('learning_area', 'order')},
        ),
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
    ]
