# Generated by Django 5.1.6 on 2026-01-24 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbc', '0003_alter_learningarea_teacher'),
        ('courses', '0006_alter_module_options_alter_module_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='learning_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='cbc.learningarea'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='learning_outcome',
            field=models.ForeignKey(blank=True, help_text='Specific learning outcome being assessed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='cbc.learningoutcome'),
        ),
    ]
