# Generated by Django 5.1.6 on 2026-01-25 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbc', '0003_alter_learningarea_teacher'),
        ('courses', '0008_alter_quiz_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='tested_outcomes',
            field=models.ManyToManyField(blank=True, help_text='Learning outcomes being assessed', related_name='assignments_m2m', to='cbc.learningoutcome'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='tested_outcomes',
            field=models.ManyToManyField(blank=True, help_text='Learning outcomes being assessed', related_name='quizzes_m2m', to='cbc.learningoutcome'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='learning_outcome',
            field=models.ForeignKey(blank=True, help_text='Primary learning outcome being assessed (deprecated in favor of tested_outcomes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='cbc.learningoutcome'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='learning_outcome',
            field=models.ForeignKey(blank=True, help_text='Primary learning outcome being assessed (deprecated in favor of tested_outcomes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='cbc.learningoutcome'),
        ),
    ]
