# Generated by Django 5.1.6 on 2026-01-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_assignment_created_at_quiz_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
